services:
  haruna:
    image: ghcr.io/haruna:latest
    restart: unless-stopped
    ports:
      - 8080:1024
    volumes:
      - haruna_data:/db
    environment:
      REST_AUTH: password
      TOPGG_AUTH: topgg_token

volumes:
  haruna_data: null